(function exposeMillenniumCatalogs() {
  const culture = (id, name, kingdomId, regionIds, summary, keywords, values, customs, commonProfessions) => ({
    id,
    name,
    kingdomId,
    regionIds,
    commonRaces: [],
    summary,
    keywords,
    upbringing: `A formação ${name} ensina a reconhecer deveres, perigos e sinais próprios de ${summary.toLowerCase()}`,
    customs,
    values,
    religion: "Varia entre culto doméstico, juramentos locais e silêncio diante dos deuses ausentes.",
    languages: ["Comum de Millennium"],
    clothing: "Vestes funcionais marcadas por origem, ofício e posição social.",
    architecture: "Construções moldadas pelo clima, pela defesa e pela memória coletiva.",
    socialRules: "Hospitalidade cria dívida; juramentos públicos têm consequência social.",
    funeraryPractices: "O nome do morto é preservado para impedir que se torne um Eco Sem Dono.",
    commonProfessions,
    startingKnowledge: keywords,
    conflicts: "Tradição, sobrevivência e interferência da Interface disputam o futuro da comunidade.",
    imageHero: "",
    imageThumbnail: "",
    emblemUrl: "",
  });

  const cultures = [
    culture("aureviana", "Aureviana", "aurevia", ["porto-millennium"], "cidades comerciais de Aurèvia", ["contratos", "etiqueta", "rotas", "moeda"], ["palavra registrada", "prosperidade", "reputação"], "Negociações importantes começam com testemunhas e terminam com um selo.", ["mercador", "escriba", "mensageiro", "guarda"]),
    culture("noctheriana", "Noctheriana", "noctheryn", ["ruinas-de-kael"], "fortalezas e vales de Noctheryn", ["juramentos", "vigília", "linhagem", "fronteira"], ["dever", "reserva", "memória"], "Promessas são pronunciadas diante de pedra escura e nunca tratadas como metáfora.", ["guarda", "sacerdote", "investigador", "funerario"]),
    culture("fronteirica", "Fronteiriça", "sem-reino", ["sul-vitrificado", "norte-branco"], "assentamentos das Terras Sem Reino", ["sobrevivência", "troca", "improviso", "autonomia"], ["liberdade", "reciprocidade", "competência"], "Toda fogueira reserva lugar para quem chega com notícia útil ou trabalho honesto.", ["cacador", "explorador", "herbalista", "construtor"]),
    culture("portuaria-millennium", "Portuária de Millennium", "aurevia", ["porto-millennium"], "cais onde Nativos e Retornados se encontram", ["idiomas", "navios", "rumores", "acolhimento"], ["adaptação", "informação", "comunidade"], "Recém-chegados recebem um nome provisório até escolherem como desejam ser lembrados.", ["marinheiro", "cozinheiro", "mensageiro", "contrabandista"]),
    culture("kaelita", "Kaelita", "noctheryn", ["ruinas-de-kael"], "comunidades erguidas junto às Ruínas de Kael", ["relíquias", "silêncio", "pedra", "Ecos"], ["cautela", "registro", "resistência"], "Objetos encontrados nas ruínas ficam uma noite isolados antes de entrar em uma casa.", ["cartografo", "historiador", "cacador-de-reliquias", "funerario"]),
    culture("vitrificada", "Vitrificada", "sem-reino", ["sul-vitrificado"], "caravanas do Sul Vitrificado", ["vidro", "calor", "caravana", "orientação"], ["movimento", "paciência", "partilha"], "Água, sombra e mapas são bens comunitários durante uma travessia.", ["explorador", "cartografo", "mercador", "alquimista"]),
    culture("branca-do-norte", "Branca do Norte", "sem-reino", ["norte-branco"], "cidades e acampamentos sob o gelo do Norte Branco", ["inverno", "memória", "caça", "abrigo"], ["preparo", "franqueza", "proteção"], "Histórias são repetidas no primeiro degelo para verificar se alguma lembrança mudou.", ["cacador", "pescador", "carpinteiro", "medico"]),
    culture("vigia-das-cortinas", "Vigia das Cortinas", "", ["cortinas"], "postos que observam o espaço entre mundos", ["Interface", "anomalias", "nomes", "portais"], ["lucidez", "documentação", "consentimento"], "Toda visão é descrita antes de ser interpretada; ninguém investiga sozinho.", ["investigador", "escriba", "cartografo", "sacerdote"]),
  ];

  const profession = (id, name, category, summary, activities, knowledge, tools, relatedClasses = []) => ({
    id,
    name,
    category,
    summary,
    activities,
    knowledge,
    tools,
    commonLocations: [],
    relatedCultures: [],
    relatedClasses,
    startingItems: tools.slice(0, 2),
    limitations: "Conhecimento profissional autoriza tentativas coerentes, não sucesso automático nem vantagem de atributo.",
    progression: "Novos métodos, contatos e receitas surgem por prática registrada, mentoria e descobertas.",
    imageThumbnail: "",
    icon: id,
  });

  const professions = [
    profession("ferreiro", "Ferreiro", "artesanato", "Forja, repara e avalia metal.", ["forjar", "reparar", "temperar"], ["ligas", "calor", "ferramentas"], ["martelo", "tenaz"], ["guerreiro"]),
    profession("medico", "Médico", "medicina", "Diagnostica e trata ferimentos com método.", ["examinar", "estabilizar", "acompanhar"], ["anatomia", "infecção", "triagem"], ["estojo médico", "ataduras"], ["acolito"]),
    profession("curandeiro", "Curandeiro", "medicina", "Combina cuidado tradicional, ervas e ritos permitidos.", ["cuidar", "preparar infusões", "observar recuperação"], ["ervas", "sintomas", "rituais locais"], ["pilão", "bolsa de ervas"], ["acolito"]),
    profession("alquimista", "Alquimista", "conhecimento", "Estuda transformações de matéria e reagentes.", ["destilar", "analisar", "formular"], ["reagentes", "toxicologia", "vidraria"], ["alambique", "frascos"], ["mago"]),
    profession("herbalista", "Herbalista", "conhecimento", "Reconhece, cultiva e conserva plantas úteis.", ["coletar", "cultivar", "secar"], ["flora", "estações", "venenos naturais"], ["faca de coleta", "herbário"]),
    profession("cacador", "Caçador", "sobrevivencia", "Rastreia criaturas e prepara expedições.", ["rastrear", "acampar", "abater"], ["pegadas", "habitats", "armadilhas"], ["corda", "kit de campo"], ["ladino", "guerreiro"]),
    profession("pescador", "Pescador", "sobrevivencia", "Lê águas, marés e criaturas aquáticas.", ["pescar", "navegar margens", "conservar alimento"], ["correntes", "iscas", "clima"], ["linha", "rede"]),
    profession("explorador", "Explorador", "exploracao", "Abre rotas e avalia territórios desconhecidos.", ["reconhecer", "orientar", "registrar risco"], ["terreno", "clima", "logística"], ["bússola", "corda"], ["ladino"]),
    profession("cartografo", "Cartógrafo", "exploracao", "Transforma observações em mapas confiáveis.", ["medir", "desenhar", "comparar rotas"], ["escala", "relevo", "navegação"], ["instrumentos de medição", "pergaminho"]),
    profession("escriba", "Escriba", "conhecimento", "Registra contratos, relatos e arquivos.", ["copiar", "catalogar", "autenticar"], ["caligrafia", "selos", "arquivos"], ["estojo de escrita", "caderno"]),
    profession("historiador", "Historiador", "conhecimento", "Compara fontes e preserva memória coletiva.", ["pesquisar", "entrevistar", "contextualizar"], ["eras", "genealogias", "fontes"], ["arquivo portátil", "lupa"]),
    profession("investigador", "Investigador", "conhecimento", "Reconstrói acontecimentos por evidências e depoimentos.", ["observar", "interrogar", "cruzar pistas"], ["procedimentos", "comportamento", "vestígios"], ["caderno", "estojo de evidências"], ["ladino"]),
    profession("mercador", "Mercador", "comercio", "Negocia mercadorias, crédito e rotas.", ["avaliar", "negociar", "organizar estoque"], ["preços", "contratos", "logística"], ["balança", "livro-caixa"]),
    profession("marinheiro", "Marinheiro", "servico", "Opera embarcações e sobrevive em travessias.", ["manobrar", "manter convés", "ler vento"], ["nós", "marés", "disciplina naval"], ["cordame", "faca naval"]),
    profession("mensageiro", "Mensageiro", "servico", "Entrega informação e objetos sob risco.", ["planejar rota", "memorizar", "entregar"], ["atalhos", "protocolos", "sinais"], ["bolsa selada", "mapa urbano"]),
    profession("cozinheiro", "Cozinheiro", "arte", "Conserva e transforma alimento para pessoas e expedições.", ["cozinhar", "conservar", "planejar provisões"], ["ingredientes", "nutrição", "fogo"], ["faca", "panela"]),
    profession("carpinteiro", "Carpinteiro", "artesanato", "Constrói e repara estruturas de madeira.", ["medir", "encaixar", "reparar"], ["madeiras", "estruturas", "ferragens"], ["serrote", "formão"]),
    profession("construtor", "Construtor", "artesanato", "Planeja e executa obras defensivas ou civis.", ["erguer", "reforçar", "avaliar estrutura"], ["materiais", "carga", "fundação"], ["nível", "marreta"]),
    profession("mineiro", "Mineiro", "sobrevivencia", "Extrai recursos e reconhece perigos subterrâneos.", ["escavar", "escorar", "identificar veio"], ["rochas", "gases", "túneis"], ["picareta", "lanterna"]),
    profession("sacerdote", "Sacerdote", "religiao", "Conduz ritos, aconselha e interpreta tradição.", ["oficiar", "escutar", "preservar rito"], ["doutrina", "símbolos", "juramentos"], ["símbolo votivo", "livro ritual"], ["acolito"]),
    profession("funerario", "Funerário", "religiao", "Prepara mortos e protege nomes contra Ecos.", ["preparar corpo", "registrar nome", "conduzir vigília"], ["costumes fúnebres", "contaminação", "Ecos"], ["mortalha", "selo de nome"], ["acolito"]),
    profession("guarda", "Guarda", "servico", "Protege pessoas, locais e procedimentos.", ["vigiar", "conter", "escoltar"], ["lei local", "rotas", "protocolo"], ["apito", "lanterna"], ["guerreiro"]),
    profession("ladrao", "Ladrão", "criminalidade", "Conhece infiltração, furtos e mercados clandestinos.", ["observar rotina", "abrir acesso", "ocultar objeto"], ["fechaduras", "vigilância", "receptadores"], ["gazuas", "bolsa oculta"], ["ladino"]),
    profession("contrabandista", "Contrabandista", "criminalidade", "Move bens e pessoas por rotas proibidas.", ["ocultar carga", "negociar passagem", "evitar fiscalização"], ["fronteiras", "códigos", "rotas secretas"], ["compartimento falso", "mapa cifrado"], ["ladino"]),
    profession("cacador-de-reliquias", "Caçador de Relíquias", "exploracao", "Localiza e recupera artefatos sem ignorar seus riscos.", ["pesquisar", "desarmar proteção", "documentar origem"], ["ruínas", "maldições", "proveniência"], ["kit de escavação", "estojo selado"], ["ladino", "mago"]),
  ];

  window.MILLENNIUM_CATALOGS_31 = Object.freeze({ cultures, professions });
}());
