(function registerMillenniumEdition3() {
  const MILLENNIUM_BUILD = "3.4.0";
  const affinity = (id, name, categoryId, bonus, domain, limit, expansion = false) => ({
    id,
    name,
    categoryId,
    bonus,
    domain,
    limit,
    expansion,
    passive: `${domain} Limite: ${limit}`,
  });

  const item = (id, name, categoryId, price, rarity, bonus, description, tags = "") => ({
    id,
    name,
    categoryId,
    price,
    rarity,
    bonus,
    description,
    tags,
    quality: rarity === "Comum" ? "Comum" : rarity === "Incomum" ? "Trabalhada" : rarity,
  });

  const rarityStats = {
    Quebrado: [6, 72, 1.9],
    Comum: [10, 88, 1.65],
    Incomum: [16, 104, 1.48],
    "Épico": [25, 116, 1.32],
    Lendário: [35, 128, 1.2],
    Mítico: [46, 138, 1.1],
    Cósmico: [58, 146, 1.02],
    Celestial: [64, 152, 1],
    Secret: [82, 164, 0.92],
  };
  const pet = (id, name, rarity, archetype, element, trait, description, index = 0) => {
    const stats = rarityStats[rarity] || rarityStats.Comum;
    return {
      id,
      name,
      rarity,
      archetype,
      role: archetype,
      element,
      bonus: {},
      td: {
        damage: stats[0] + (index % 4),
        range: stats[1] + ((index * 7) % 18),
        cooldown: Math.max(0.72, stats[2] - (index % 3) * 0.04),
      },
      trait,
      description,
      catalog: "Edição Reforjada 3.0",
    };
  };

  const baseItems = [
    item("adaga", "Adaga", "arma", 20, "Comum", { hab: 1 }, "Lâmina curta para precisão, ocultação e trabalho próximo.", "leve, curta"),
    item("espada-curta", "Espada Curta", "arma", 40, "Comum", { for: 2 }, "Arma versátil para espaços apertados.", "corte, curta"),
    item("espada-longa", "Espada Longa", "arma", 80, "Incomum", { for: 3 }, "Alcance e alavanca exigem espaço para trabalhar.", "corte, longa"),
    item("machado-guerra", "Machado de Guerra", "arma", 80, "Incomum", { for: 3 }, "Ferramenta de ruptura pesada, visível e cansativa.", "impacto, pesada"),
    item("machado-mao", "Machado de Mão", "arma", 50, "Comum", { for: 2 }, "Pode ser usado como ferramenta e arma curta.", "impacto, curta"),
    item("lanca", "Lança", "arma", 50, "Comum", { hab: 2 }, "Controle de distância e formação; fraca em corredores estreitos.", "perfuração, haste"),
    item("alabarda", "Alabarda", "arma", 100, "Raro", { for: 3 }, "Arma de haste para guarda e quebra de formação.", "haste, pesada"),
    item("arco-curto", "Arco Curto", "arma", 50, "Comum", { hab: 2 }, "Ágil, silencioso e limitado por munição.", "distância, munição"),
    item("arco-longo", "Arco Longo", "arma", 90, "Incomum", { hab: 3 }, "Grande alcance, exige força, postura e espaço.", "distância, longa"),
    item("besta", "Besta", "arma", 100, "Raro", { hab: 3 }, "Disparo estável com recarga lenta e ruidosa.", "distância, mecânica"),
    item("maca", "Maça", "arma", 50, "Comum", { for: 2 }, "Impacto confiável contra proteção rígida.", "impacto"),
    item("martelo-guerra", "Martelo de Guerra", "arma", 100, "Raro", { for: 3 }, "Ruptura brutal que cobra tempo e equilíbrio.", "impacto, pesada"),
    item("cajado-arcano", "Cajado Arcano", "arma", 80, "Incomum", { pod: 3 }, "Foco longo para ritos, canalização e defesa.", "foco, ritual"),
    item("varinha-mistica", "Varinha Mística", "arma", 50, "Comum", { pod: 2 }, "Foco discreto para controle fino de essência.", "foco, leve"),
    item("grimorio-arcano", "Grimório Arcano", "arma", 120, "Raro", { pod: 3 }, "Fórmulas registradas; depende de leitura, preparo e preservação.", "foco, conhecimento"),
    item("vestes-tecido", "Vestes de Tecido", "armadura", 20, "Comum", { def: 1 }, "Proteção leve que não limita movimento.", "leve"),
    item("armadura-couro", "Armadura de Couro", "armadura", 50, "Comum", { def: 2 }, "Proteção flexível contra cortes superficiais.", "leve"),
    item("cota-malha", "Cota de Malha", "armadura", 100, "Incomum", { def: 3 }, "Boa contra corte, pesada e ruidosa.", "média, metal"),
    item("armadura-laminada", "Armadura Laminada", "armadura", 150, "Raro", { def: 4 }, "Placas móveis equilibram proteção e mobilidade.", "média, placas"),
    item("armadura-placas", "Armadura de Placas", "armadura", 250, "Épico", { def: 5 }, "Proteção superior com custo de peso, calor e manutenção.", "pesada, placas"),
    item("broquel", "Broquel", "escudo", 20, "Comum", { def: 1 }, "Escudo pequeno para desvio e duelo.", "leve"),
    item("escudo-madeira", "Escudo de Madeira", "escudo", 50, "Comum", { def: 2 }, "Cobertura acessível, vulnerável a fogo e impacto repetido.", "madeira"),
    item("escudo-ferro", "Escudo de Ferro", "escudo", 80, "Incomum", { def: 3 }, "Cobertura resistente que exige braço treinado.", "metal"),
    item("escudo-torre", "Escudo Torre", "escudo", 180, "Raro", { def: 5 }, "Proteção de formação; reduz mobilidade e visão lateral.", "pesado, cobertura"),
    item("luvas-couro", "Luvas de Couro", "acessorio", 30, "Comum", { hab: 1 }, "Aderência e proteção das mãos.", "utilidade"),
    item("braceletes-guerra", "Braceletes de Guerra", "acessorio", 70, "Incomum", { res: 2 }, "Estabilizam guarda e absorvem impacto localizado.", "defesa"),
    item("botas-viajante", "Botas do Viajante", "acessorio", 30, "Comum", { vel: 1 }, "Protegem em marcha e terreno irregular.", "viagem"),
    item("botas-leves", "Botas Leves", "acessorio", 70, "Incomum", { vel: 2 }, "Passos rápidos em terreno firme.", "leve"),
    item("capa-cacador", "Capa do Caçador", "acessorio", 70, "Incomum", { vel: 2 }, "Quebra silhueta e protege de clima moderado.", "furtividade"),
    item("anel-forca", "Anel da Força", "acessorio", 70, "Incomum", { for: 2 }, "Selo de treino físico; não substitui postura.", "vínculo"),
    item("colar-vitalidade", "Colar da Vitalidade", "acessorio", 70, "Incomum", { res: 2 }, "Ajuda a sustentar esforço, sem apagar ferimentos.", "vínculo"),
    item("amuleto-arcano", "Amuleto Arcano", "acessorio", 70, "Incomum", { pod: 2 }, "Foco de reserva para ritos preparados.", "foco"),
    item("tiara-arcana", "Tiara Arcana", "acessorio", 120, "Raro", { pod: 3 }, "Organiza fluxo de essência e expõe o usuário a interferência mental.", "foco"),
    item("pocao-vida", "Poção de Vida", "consumivel", 20, "Comum", { hp: 20 }, "Auxilia recuperação; não fecha ferimento grave instantaneamente.", "cura"),
    item("pocao-grande-vida", "Poção Grande de Vida", "consumivel", 50, "Incomum", { hp: 50 }, "Recuperação forte que exige repouso e tolerância.", "cura"),
    item("pocao-poder", "Poção de Poder", "consumivel", 20, "Comum", { pp: 20 }, "Recupera essência moderada e produz tremor após abuso.", "essência"),
    item("pocao-grande-poder", "Poção Grande de Poder", "consumivel", 50, "Incomum", { pp: 50 }, "Reserva concentrada com risco de sobrecarga.", "essência"),
    item("antidoto", "Antídoto", "consumivel", 15, "Comum", {}, "Remove toxina compatível quando usada a tempo.", "medicina"),
    item("bandagem", "Bandagem", "consumivel", 10, "Comum", { hp: 10 }, "Contém sangramento e protege a lesão.", "medicina"),
    item("kit-medico", "Kit Médico", "consumivel", 40, "Incomum", { hp: 30 }, "Ferramentas para estabilização por alguém treinado.", "medicina"),
    item("racao-viagem", "Ração de Viagem", "consumivel", 5, "Comum", {}, "Um dia de alimentação conservada.", "suprimento"),
    item("cantil", "Cantil", "especial", 5, "Comum", {}, "Recipiente de água; vazio não resolve sede.", "suprimento"),
    item("tocha", "Tocha", "especial", 2, "Comum", {}, "Ilumina, denuncia posição e consome combustível.", "luz"),
    item("corda-15m", "Corda 15 m", "especial", 10, "Comum", {}, "Ferramenta de escalada, resgate e amarração.", "ferramenta"),
    item("kit-acampamento", "Kit de Acampamento", "especial", 40, "Incomum", {}, "Abrigo, preparo e descanso em viagem.", "viagem"),
    item("gazua", "Gazua", "especial", 30, "Incomum", { hab: 1 }, "Ferramenta de fechadura que exige conhecimento e tempo.", "ladino"),
  ];

  const petSpecs = [
    ["rato-de-vela", "Rato de Vela", "Quebrado", "Suporte", "Fogo", "Acende uma luz curta; apaga quando assustado.", "Uma chama pequena sobrevive entre seus bigodes."],
    ["corvo-desafinado", "Corvo Desafinado", "Quebrado", "Controle", "Som", "Interrompe um inimigo fraco com canto imprevisível.", "Ele erra todas as notas, menos a que importa."],
    ["lesma-de-ferro", "Lesma de Ferro", "Quebrado", "Defesa", "Metal", "Bloqueia passagem estreita, mas se move lentamente.", "Uma muralha minúscula que nunca chega cedo."],
    ["mimico-de-bolso", "Mímico de Bolso", "Quebrado", "Utilidade", "Vazio", "Armazena um item pequeno e às vezes o devolve errado.", "Seus dentes guardam mais do que deveriam."],
    ["sapo-de-cinza", "Sapo de Cinza", "Quebrado", "Debuff", "Cinzas", "Solta fumaça curta que reduz visão.", "Coaxa como uma fogueira morrendo."],
    ["aranha-de-pano", "Aranha de Pano", "Quebrado", "Suporte", "Tinta", "Repara pequenas rasgaduras e redes.", "Costura o que o medo rasgou."],
    ["cao-sem-sombra", "Cão Sem Sombra", "Quebrado", "Rastreio", "Sombras", "Fareja medo recente, mas não cheiros comuns.", "Algo esqueceu de desenhar sua sombra."],
    ["peixe-de-vidro", "Peixe de Vidro", "Quebrado", "Especial", "Vidro", "Flutua por instantes e revela reflexos falsos.", "Nada em um mar que só existe nos espelhos."],
    ["besouro-tocador", "Besouro Tocador", "Quebrado", "Buff", "Música", "Produz ritmo que acelera recarga baixa.", "Seu casco é um tambor de guerra ruim e honesto."],
    ["galo-sepulcral", "Galo Sepulcral", "Quebrado", "Alerta", "Espírito", "Canta antes de emboscadas, inclusive algumas inexistentes.", "Acorda vivos, mortos e suspeitas."],
    ["lobo-de-bruma", "Lobo de Bruma", "Comum", "Ataque", "Névoa", "Causa mais dano a alvos lentos.", "Caça onde os olhos deixam de ajudar."],
    ["raposa-de-cobre", "Raposa de Cobre", "Comum", "Utilidade", "Metal", "Encontra fragmentos em rotas urbanas.", "Conhece todo atalho que já foi vendido."],
    ["coruja-das-ruinas", "Coruja das Ruínas", "Comum", "Alcance", "Eco", "Aumenta visão em mapas noturnos.", "Seus olhos leem paredes como páginas."],
    ["javali-de-musgo", "Javali de Musgo", "Comum", "Defesa", "Natureza", "Empurra inimigos leves.", "Uma colina teimosa com presas."],
    ["gato-de-fuligem", "Gato de Fuligem", "Comum", "Controle", "Fumaça", "Cria uma área breve de fumaça.", "Sempre aparece depois do incêndio."],
    ["falcao-da-cortina", "Falcão da Cortina", "Comum", "Ataque", "Ar", "Prioriza inimigos voadores.", "Vê costuras entre um mundo e outro."],
    ["cervo-de-espinhos", "Cervo de Espinhos", "Comum", "Suporte", "Madeira", "Regenera lentamente a base.", "Raízes brotam onde seus cascos sangram."],
    ["cao-de-oficina", "Cão de Oficina", "Comum", "Utilidade", "Ferrugem", "Reduz o custo do primeiro upgrade.", "Carrega ferramentas e julga todo reparo."],
    ["serpente-de-areia", "Serpente de Areia", "Comum", "Debuff", "Areia", "Aplica lentidão em rota seca.", "O deserto se move dentro de suas escamas."],
    ["carneiro-de-pedra", "Carneiro de Pedra", "Comum", "Defesa", "Terra", "Recebe o primeiro impacto de elite.", "Seu crânio conhece portas que ainda não cederam."],
    ["mariposa-lunar", "Mariposa Lunar", "Comum", "Suporte", "Lunar", "Aumenta alcance durante ondas noturnas.", "Poeira prateada marca o caminho seguro."],
    ["lontra-de-cristal", "Lontra de Cristal", "Comum", "Controle", "Cristal", "Cria um obstáculo frágil.", "Brinca com estilhaços como se fossem água."],
    ["pantera-do-eclipse", "Pantera do Eclipse", "Incomum", "Ataque", "Eclipse", "Ataca melhor quando luta isolada.", "O dia termina quando ela abre os olhos."],
    ["urso-sineiro", "Urso Sineiro", "Incomum", "Defesa", "Som", "Provoca inimigos e resiste a controle.", "Cada passo soa como um funeral distante."],
    ["hiena-carmesim", "Hiena Carmesim", "Incomum", "Ataque", "Sangue", "Fortalece-se contra alvos feridos.", "Ri porque já sentiu o cheiro do fim."],
    ["ibis-do-oraculo", "Íbis do Oráculo", "Incomum", "Suporte", "Estelar", "Revela inimigos ocultos periodicamente.", "Sua sombra escreve avisos no chão."],
    ["escorpiao-de-bronze", "Escorpião de Bronze", "Incomum", "Debuff", "Ferrugem", "Aplica corrosão acumulativa.", "Foi construído para uma guerra que perdeu o nome."],
    ["cavalo-de-nevoa", "Cavalo de Névoa", "Incomum", "Mobilidade", "Névoa", "Pode ser reposicionado uma vez por onda.", "Galopa por atalhos que duram um suspiro."],
    ["macaco-runico", "Macaco Rúnico", "Incomum", "Utilidade", "Arcana", "Copia temporariamente um upgrade básico adjacente.", "Aprende símbolos antes de entender proibições."],
    ["tartaruga-mar-negro", "Tartaruga de Mar Negro", "Incomum", "Defesa", "Água", "Cria escudo contra projéteis.", "Carrega uma noite inteira no casco."],
    ["lince-estelar", "Lince Estelar", "Incomum", "Alcance", "Estelar", "Acertos precisos alimentam o combo.", "Segue constelações que ninguém registrou."],
    ["abutre-do-pecado", "Abutre do Pecado", "Incomum", "Economia", "Ruína", "Gera fragmento extra ao derrotar elites.", "Nunca desperdiça o que uma guerra deixa."],
    ["quimera-tres-fomes", "Quimera das Três Fomes", "Épico", "Híbrido", "Entropia", "Alterna fogo, veneno e impacto.", "Três gargantas discutem qual mundo devorar."],
    ["cavaleiro-sem-cavaleiro", "Cavaleiro Sem Cavaleiro", "Épico", "Defesa", "Espírito", "Bloqueia uma rota como armadura vazia.", "A armadura voltou. Seu dono, não."],
    ["dragao-de-oficina", "Dragão de Oficina", "Épico", "Ataque", "Fogo", "Acumula calor e explode após uma sequência.", "Parafusos seguram um coração de fornalha."],
    ["dama-do-espelho", "Dama do Espelho", "Épico", "Controle", "Vidro", "Cria duplicata ilusória de pet adjacente.", "Nenhum reflexo concorda sobre seu rosto."],
    ["leao-ultima-aurora", "Leão da Última Aurora", "Épico", "Suporte", "Solar", "Fortalece aliados quando a base está baixa.", "Ruge como se o sol ainda devesse algo."],
    ["hidra-de-pantano", "Hidra de Pântano", "Épico", "Debuff", "Veneno", "Cada estrela libera uma cabeça funcional.", "Toda cabeça lembra uma fome diferente."],
    ["fenrir-mil-pegadas", "Fenrir das Mil Pegadas", "Lendário", "Ataque", "Natureza", "Caça chefes e acelera a equipe.", "Todos os clãs reconhecem suas pegadas."],
    ["serafim-fraturado", "Serafim Fraturado", "Lendário", "Suporte", "Celestial", "Previne uma derrota e fica ferido depois.", "Metade do halo ainda acredita em salvação."],
    ["basilisco-livro-carmesim", "Basilisco do Livro Carmesim", "Lendário", "Controle", "Sangue", "Petrifica temporariamente uma elite sob condição.", "Cobra dívidas olhando nos olhos."],
    ["grifo-sol-partido", "Grifo de Sol Partido", "Lendário", "Híbrido", "Solar", "Ataque aéreo e aura de liderança.", "Suas penas douradas queimam quem as reivindica."],
    ["leviata-vidro-negro", "Leviatã de Vidro Negro", "Mítico", "Controle", "Abismo", "Altera a rota por uma onda e quebra parte do mapa.", "O mar se torna espelho quando ele sobe."],
    ["cervo-primeiro-bosque", "Cervo do Primeiro Bosque", "Mítico", "Suporte", "Natureza", "Restaura espaço destruído e remove corrupção.", "Lembra a floresta anterior aos deuses."],
    ["cao-vazio-portas", "Cão do Vazio Entre Portas", "Cósmico", "Especial", "Vazio", "Teleporta entre dois pontos e perde estabilidade.", "Fareja passagens que a Interface nega."],
    ["arauto-sete-esferas", "Arauto das Sete Esferas", "Celestial", "Suporte", "Constelação", "Escolhe uma bênção de mapa e assume um juramento.", "Sete órbitas pesam sobre sua promessa."],
    ["crianca-esquecida", "A Criança que a Janela Esqueceu", "Secret", "Especial", "Paradoxo", "Sua habilidade nasce de uma cadeia oculta do Codex.", "A Interface não consegue registrar seu verdadeiro nome."],
  ].map((entry, index) => pet(...entry, index));

  const kingdoms = [
    ["limiar", "Limiar das Cortinas", "Concordato das Lanternas", "Cidade-estado mista que registra Retornados e vende neutralidade."],
    ["solcaris", "Solcaris · Reino do Sol Partido", "Aurelian IX", "Monarquia sagrada que transforma heroísmo em autoridade estatal."],
    ["elarion", "Elarion · Corte das Folhas Douradas", "Casas de Memória", "Oligarquia élfica que preserva o passado e poda versões dissidentes."],
    ["grivemarch", "Grivemarch · Liga Ferrugínea", "Conselho de Oficinas", "República industrial que reproduz tecnologia da Interface."],
    ["nocthar", "Nocthar · Principado Carmesim", "Príncipe Sevran Vael", "Casas credoras mantêm paz por sangue, etiqueta e dívida."],
    ["azrakar", "Azrakar · Domínio das Cinzas", "Confederação de Pactos", "Fortalezas demoníacas em guerra contra a soberania divina."],
    ["vargra", "Vargra · Mil Pegadas", "Assembleias de Clã", "Confederação que protege rotas, autonomia e territórios vivos."],
    ["khar-dum", "Khar-Dum · Tronos da Forja", "Tribunal dos Mestres", "Clãs controlam minas, infraestrutura e uma máquina divina adormecida."],
    ["nymira", "Nymira · República das Marés", "Conselho de Arquistas", "Capitães eleitos governam rotas aquáticas e arquivos submersos."],
    ["umbra-nox", "Umbra Nox · Estado do Véu", "Magistrados Mascarados", "Abrigo político e mercado de informação feito de identidades frágeis."],
    ["vel-khar", "Vel-Khar · Necrópole Livre", "Senado dos Nomes Persistentes", "Mortos conscientes lutam por continuidade jurídica e memória."],
    ["pecado-partido", "Reino do Pecado Partido", "Sem soberania", "Ruínas do primeiro reino de Heróis-recipientes."],
  ].map(([id, name, ruler, description]) => ({ id, name, ruler, description }));

  const biomes = [
    ["cruzamento-das-cortinas", "Cruzamento das Cortinas", "Limiar", "Ruas de mundos diferentes se sobrepõem; portas falsas e ecos caçam nomes."],
    ["aldeia-das-folhas-douradas", "Aldeia das Folhas Douradas", "Elarion", "Árvores-arquivo guardam uma comunidade onde predadores apagam rastros."],
    ["arena-das-sete-esferas", "Arena das Sete Esferas", "Solcaris", "Anfiteatro astral onde peso, luz e som mudam por esfera."],
    ["sociedade-das-laminas", "Sociedade das Lâminas", "Cortinas", "Fortaleza entre pontes espirituais, espadas animadas e juramentos hostis."],
    ["pantano-sinos-afogados", "Pântano dos Sinos Afogados", "Nymira", "Torres submersas convocam mortos quando a maré toca bronze fúnebre."],
    ["mar-vidro-negro", "Mar de Vidro Negro", "Sul Vitrificado", "Deserto vitrificado que vira oceano sob a lua e reflete identidades."],
    ["jardins-de-carne", "Jardins de Carne", "Sem reino", "Floresta orgânica de um deus enterrado; plantas sentem medo."],
    ["cordilheira-dente-branco", "Cordilheira do Dente Branco", "Vargra", "Montanhas de gelo eterno, caça territorial e espíritos antigos."],
    ["ermos-ferrugem", "Ermos da Ferrugem", "Grivemarch", "Planícies industriais de chuva ácida, máquinas e poeira metálica."],
    ["vale-carmesim", "Vale Carmesim", "Nocthar", "Vinhedos e bancos de sangue onde contratos valem mais que espadas."],
    ["deserto-nomes-queimados", "Deserto dos Nomes Queimados", "Azrakar", "Tempestades roubam palavras, identidades e pactos mal protegidos."],
    ["reino-do-pecado-partido", "Reino do Pecado Partido", "Pecado Partido", "Cidades empilhadas num abismo de luz morta reagem à culpa."],
    ["catacumbas-afogadas", "Catacumbas Afogadas", "Nymira", "Arquivo funerário sob pressão, portas de maré e mortos inquietos."],
    ["bosque-faces-quietas", "Bosque das Faces Quietas", "Umbra Nox", "Cascas imitam rostos e trilhas retornam para pessoas diferentes."],
    ["campos-dos-ossos", "Campos dos Ossos", "Vel-Khar", "Uma guerra não encerrada deixou cavaleiros mortos e minas antigas."],
    ["coracao-khar-dum", "Coração de Khar-Dum", "Khar-Dum", "Minas quentes escondem máquinas anteriores à Queda."],
  ].map(([id, name, region, description]) => ({ id, name, region, description }));

  const factions = [
    ["concordato-lanternas", "Concordato das Lanternas", "Limiar", "Neutralidade, cadastro e monopólio de informação."],
    ["ultima-aurora", "Igreja da Última Aurora", "Solcaris", "Transformar o Despertar em cruzada e controlar Heróis."],
    ["nomes-lembrados", "Corte dos Nomes Lembrados", "Elarion", "Controlar memória legítima e versões do passado."],
    ["bolsa-ferruginea", "Bolsa Ferrugínea", "Grivemarch", "Privatizar tecnologia e serviços da Interface."],
    ["livro-carmesim", "Livro Carmesim", "Nocthar", "Fazer toda dívida importante atravessar suas casas."],
    ["pacto-cinzas", "Pacto das Cinzas", "Azrakar", "Destruir soberania divina por contrato e guerra."],
    ["mil-pegadas", "Assembleia das Mil Pegadas", "Vargra", "Proteger território, rotas naturais e autonomia cultural."],
    ["elmos-vazios", "Ordem dos Elmos Vazios", "Todo Millennium", "Impedir que fragmentos divinos nasçam dentro de Heróis."],
    ["coro-sem-nome", "Coro Sem Nome", "Cortinas", "Dissolver identidades numa consciência coletiva da Interface."],
    ["cartografos-ultima-porta", "Cartógrafos da Última Porta", "Fronteiras", "Mapear Cortinas e encontrar uma saída real."],
    ["senado-nomes", "Senado dos Nomes Persistentes", "Vel-Khar", "Garantir reconhecimento legal e proteger âncoras dos mortos."],
    ["irmandade-cinzas", "Irmandade das Cinzas", "Azrakar", "Negociar segredos infernais e favores perigosos."],
    ["cofre-mares", "Cofre das Marés", "Nymira", "Controlar rotas, resgates e informação marítima."],
    ["aurora-ferida", "Igreja da Aurora Ferida", "Limiar", "Buscar redenção e cura sem submissão aos deuses."],
  ].map(([id, name, region, description]) => ({
    id,
    name,
    region,
    description,
    levels: "Observado · Reconhecido · Juramentado · Voz",
    benefit: "Contratos, relações e caminhos narrativos próprios.",
    risk: "Todo vínculo cobra posição, dever e consequência.",
    quote: "Nenhum juramento é apenas um botão.",
  }));

  const npcs = [
    ["mirella-voss", "Mirella Voss", "Regente de Limiar", "Mantém a cidade neutra enquanto apaga desaparecidos do cadastro."],
    ["irma-merrow", "Irmã Merrow", "Ordem dos Elmos Vazios", "Anjo fraturado que removeu o próprio halo para fugir da incubação."],
    ["aurelian-ix", "Aurelian IX", "Rei de Solcaris", "Deseja ser pai dos novos Heróis; sua linhagem alimenta o Fragmento Solar."],
    ["serafine-ouro", "Serafine de Ouro", "Matriarca da Última Aurora", "Converte marcas heroicas em fé e ouve um deus faminto."],
    ["aelthir-vey", "Aelthir Vey", "Primeiro Arquivista", "Preserva memórias e esconde um túmulo dentro do esquecimento da filha."],
    ["nemea-folha-cega", "Nemea Folha-Cega", "Rebelde arquivista", "Carrega milhares de lembranças confiscadas e perde a própria identidade."],
    ["brakka-bobina", "Brakka Bobina-Nona", "Chanceler de Grivemarch", "Criou uma cópia da Janela que começou a escolher usuários."],
    ["sevran-vael", "Sevran Vael", "Príncipe de Nocthar", "Seu corpo é compartilhado por três antigos credores."],
    ["ysolde-rubra", "Ysolde Rubra", "Contadora Carmesim", "Deseja destruir a economia de sangue que a tornou poderosa."],
    ["kael-zhar", "Kael-Zhar", "Marechal das Cinzas", "Seu pacto o obriga a prolongar uma guerra que deseja encerrar."],
    ["ilyra-sem-fagulha", "Ilyra Sem-Fagulha", "Negociadora de Azrakar", "Conhece o nome verdadeiro do primeiro deus morto."],
    ["kavra-presa-branca", "Kavra Presa-Branca", "Voz de Vargra", "Protege território e carrega culpa por ataques preventivos."],
    ["escriba-mudo", "O Escriba Mudo", "Avatar da Interface", "Registra tudo que recebe nome, menos a Criança Esquecida."],
    ["elias-primeira-cova", "Elias da Primeira Cova", "Primeiro Herói", "Tenta salvar pessoas enquanto o deus da obediência cresce dentro dele."],
    ["mara-sete-cicatrizes", "Mara Sete-Cicatrizes", "Caçadora independente", "Busca a irmã que escolheu permanecer guardiã de um túmulo."],
    ["tess-ferro-morno", "Tess Ferro-Morno", "Forjadora de relíquias", "Cada peça criada recebe uma de suas memórias."],
  ].map(([id, name, role, description]) => ({ id, name, role, description }));

  const rulesChapters = [
    [1, "Identidade e autoria", "Controle seu personagem, não o corpo, a mente ou o destino de outro.", "Millennium é interpretação narrativa contínua. Intenção vem antes do resultado; preparação tem peso; poder exige preço; consequências continuam valendo; arbitragem deve ser explicável."],
    [2, "Continuidade no WhatsApp", "Localização, tempo e consequências conectam todas as cenas.", "O WhatsApp é o palco principal. Regiões, cenas privadas e missões respeitam localização atual, âncoras temporais e resumo final quando houver consequência pública."],
    [3, "Arbitragem sem dados", "Coerência, contexto e ação escrita substituem sorteios.", "O Oráculo considera fatos, preparação, posição, estados, compatibilidade, atributos, conhecimento e clareza. Resultados podem ser válidos, válidos com custo, parciais, contestados ou orientados para reescrita."],
    [4, "Criação do personagem", "Crie uma pessoa capaz de existir socialmente, não só uma combinação de combate.", "Registre origem, raça, cultura, reino, classe, ofício, objetivo, medo e limites do jogador. Distribua 20 pontos entre cinco atributos, mínimo 2 e máximo 6 antes dos bônus."],
    [5, "Atributos e estados", "FOR, VEL, HAB, RES e POD autorizam possibilidades específicas.", "Atributo alto não substitui percepção, conhecimento ou técnica. Ferimentos e essência usam estados narrativos; barras do site são apoio, não matemática automática de cena."],
    [6, "Poderes e técnicas", "Um Poder central, custos verificáveis e contramedidas reais.", "Todo poder registra fonte, função, alcance, sinais, custo, limitações, ao menos duas contramedidas e proibições. Técnicas evoluem dos Graus I a V com preço crescente."],
    [7, "Afinidades", "Afinidade orienta o poder; raridade mede estranheza e risco.", "A Revelação oferece três Ecos e o player escolhe um. Elemental 50%, Subelemental 25%, Espiritual 13%, Celestial 8% e Cósmica 4%. Nenhuma afinidade garante vitória."],
    [8, "Evolução", "XP nasce de participação validada, treino e consequência.", "Todo nível registra jornada; a cada 5 níveis há Ponto de Desenvolvimento; a cada 10, técnica; a cada 20, ruptura; a cada 50, feito lendário. Minigames não substituem evolução textual."],
    [9, "Mundo, política e viagem", "Reinos não são times morais e atalhos sempre trocam tempo por risco.", "Millennium é persistente. Ferimentos, dívidas, tratados, escassez e escolhas políticas continuam. Descobertas do Codex passam por Rumor, Observação, Confirmação e Domínio."],
    [10, "Guildas e facções", "Vínculos criam autoridade, dever e consequência.", "Guildas registram cargos, tesouro, contratos, território e conflitos. Guerra exige motivo, objetivo, termos, zonas de risco e duração. Facções permanecem bloqueadas até abertura narrativa pelo Oráculo."],
    [11, "Economia e itens", "PO pertence ao mundo; MC e fragmentos pertencem à Interface.", "Itens possuem qualidade, função, tags e limite. Bônus numérico serve ao site e minigames; nunca ignora material, distância, posição ou defesa no WhatsApp."],
    [12, "Pets e minigames", "Companheiros têm vínculo, estado e limites.", "Fusão exige duas cópias idênticas com a mesma estrela. Hunt, Mira e Tower entregam recursos e coleção, nunca resolvem missões narrativas automaticamente."],
    [13, "Conduta e segurança", "Respeito, consentimento e integridade vêm antes de progressão.", "Sem godmodding, metagame, spam de ações, abuso de bugs ou perseguição. Denúncias preservam contexto e o Oráculo pode orientar, mutar, suspender ou banir com motivo registrado."],
  ].map(([order, name, summary, full]) => ({ id: `regra-${order}`, order, name, summary, full }));

  const tutorialSteps = [
    [0, "A Interface abriu", "Entenda que o site registra sua jornada; o RPG acontece continuamente pelo WhatsApp."],
    [1, "Aceite o pacto de convivência", "Leia as regras atuais. Uma nova versão exige novo aceite."],
    [2, "Registre o Escolhido", "Crie ficha, origem, raça, cultura, classe, ofício, objetivo, medo, avatar e banner."],
    [3, "Distribua os atributos", "Use exatamente 20 pontos: mínimo 2 e máximo 6 em cada atributo antes dos bônus."],
    [4, "Abra o Portal da Ressonância", "Consuma essência, revele três Ecos e registre uma afinidade definitiva."],
    [5, "Veja o Espelho da Alma", "Confira seu perfil público, equipe título e cosméticos e ajuste privacidade."],
    [6, "Entre na Rede de Ecos", "Use Global, mensagens diretas e guilda. Clique no nome para abrir o perfil."],
    [7, "Escolha uma missão", "Marque a missão ativa, jogue no WhatsApp e envie a conclusão ao Oráculo."],
    [8, "Relate treino e criações", "Treino, poder e técnica entram na fila com contexto, custo e limites."],
    [9, "Explore o Codex", "Diferencie conhecimento do player de conhecimento confirmado pelo personagem."],
    [10, "Use sua autonomia", "Compre, forje, colete Passe, funda pets, administre inventário e anuncie itens sem fila manual."],
    [11, "Desafie a Interface", "Mira, Hunt e Tower usam energia e recompensam desempenho; não decidem cenas narrativas."],
    [12, "Deixe uma marca", "Sua jornada começa quando uma escolha produz consequência no mundo."],
  ].map(([order, name, description]) => ({ id: `despertar-${order}`, order, name, description }));

  const cosmetics = [
    ["moldura-primeira-fenda", "Moldura da Primeira Fenda", "Raro", "Moldura", "Vidro ritual rachado ao redor do avatar."],
    ["moldura-elmo-vazio", "Moldura do Elmo Vazio", "Épico", "Moldura", "Metal negro e halo fraturado."],
    ["moldura-sete-esferas", "Órbita das Sete Esferas", "Lendário", "Moldura", "Sete marcas orbitais respondem ao status online."],
    ["banner-limiar", "Banner de Limiar", "Incomum", "Banner", "Lanternas e chuva sobre o portal dos Retornados."],
    ["banner-tumulos", "Treze Túmulos", "Épico", "Banner", "Silhuetas abertas durante o Primeiro Despertar."],
    ["banner-sol-partido", "Sol Partido", "Lendário", "Banner", "A luz de Solcaris se rompe atrás do personagem."],
    ["aura-cinzas", "Aura de Cinzas Lentas", "Raro", "Efeito de Perfil", "Partículas de cinza acompanham o cartão."],
    ["aura-cortina", "Cortina Instável", "Mítico", "Efeito de Perfil", "O cartão oscila como uma porta entre mundos."],
    ["token-retornado", "Token Retornado", "Comum", "Token", "Marca de quem acordou em Millennium."],
    ["token-testemunha", "Token Testemunha da Fenda", "Épico", "Token", "Registro de um evento mundial concluído."],
  ].map(([id, name, rarity, category, description]) => ({ id, name, rarity, category, effect: description, description, bonus: {} }));

  const marketListings = baseItems.map((entry) => ({
    ...entry,
    id: `mercado-${entry.id}`,
    sourceItemId: entry.id,
    description: `${entry.description} ${entry.tags ? `Tags: ${entry.tags}.` : ""}`,
  }));

  const shardOffers = [
    ["traje-despertar", "Traje do Despertar", "Fragmentos de Mira", 220, "Épico", "Cosmético", "Visual sazonal do Primeiro Despertar."],
    ["moldura-luz-inicial", "Moldura Luz Inicial", "Marcas de Caçada", 180, "Raro", "Moldura", "Borda dourada da Primeira Janela."],
    ["ticket-reliquia", "Ticket de Relíquia", "Runas Partidas", 90, "Incomum", "Ticket", "Uma invocação no banner de itens."],
    ["passe-premium-sazonal", "Passe Premium", "Fragmentos do Despertar", 2000, "Lendário", "Passe", "Liberação por esforço extremo, sem dinheiro real."],
    ["pet-heroi-quebrado", "Pet do Herói Quebrado", "Fragmentos do Despertar", 1200, "Celestial", "Pet", "Companheiro sazonal montado por partes secretas."],
    ["energia-selada", "Energia Selada x5", "Fragmentos de Mira", 65, "Comum", "Energia", "Recupera cinco pontos de energia."],
    ["caixa-materiais", "Caixa de Materiais de Hunt", "Marcas de Caçada", 120, "Incomum", "Material", "Entrega materiais rotativos de biomas conhecidos."],
    ["token-cartografo", "Token Cartógrafo da Última Porta", "Runas Partidas", 240, "Raro", "Token", "Insígnia de exploração para o perfil."],
    ["banner-pantano", "Banner dos Sinos Afogados", "Marcas de Caçada", 360, "Épico", "Banner", "Cosmético de incursões profundas."],
    ["reliquia-temporaria", "Relíquia de Defesa Temporária", "Fragmentos do Despertar", 480, "Épico", "Item", "Item digital para Tower Defense e coleção."],
  ].map(([id, name, shop, cost, rarity, type, description]) => ({ id, name, shop, cost, rarity, type, description }));

  const future = (days, hour = 22) => {
    const date = new Date(Date.now() + days * 86400000);
    date.setHours(hour, 0, 0, 0);
    return date.toISOString();
  };

  window.MILLENNIUM_V3_CONTENT = {
    build: MILLENNIUM_BUILD,
    settings: {
      seasonName: "Temporada I · Despertar dos Heróis",
      rulesVersion: "3.0",
      factionsUnlocked: false,
      onboardingVersion: "3.0",
      termsText: "Millennium é um RPG textual contínuo jogado principalmente pelo WhatsApp. A Interface do Oráculo registra fichas, inventário, economia, chats de apoio, missões e decisões administrativas; ela não substitui interpretação nem concede vitória automática. Ao entrar, você concorda em respeitar autoria limitada, consentimento, localização, ferimentos, custos, consequências e decisões explicadas do Oráculo; não usar metagame, godmodding, spam de ações, manipulação do navegador, abuso de bugs, assédio ou fraude econômica; denunciar problemas com contexto; e proteger a experiência coletiva. Punições devem ter motivo registrado e podem incluir orientação, mute, suspensão ou banimento. A versão vigente deste termo precisa ser aceita novamente quando atualizada.",
      globalNotice: "A Interface do Oráculo está desperta. O WhatsApp conduz a história; este lugar preserva suas marcas.",
    },
    collections: {
      races: [
        { id: "humano", name: "Humano", bonus: { for: 1, vel: 1, hab: 1, res: 1, pod: 1 }, passive: "Adaptabilidade: após observar um método, reconhece um padrão e reduz uma desvantagem específica. Não copia poderes." },
        { id: "elfo", name: "Elfo", bonus: { hab: 3, pod: 2 }, passive: "Sentidos Aguçados: percebe detalhes, rastros e trajetórias com foco, visão ou tempo de observação." },
        { id: "goblin", name: "Goblin", bonus: { hab: 3, vel: 2 }, passive: "Improvisador Nato: cria solução provisória com material disponível; toda improvisação recebe desgaste ou risco." },
        { id: "anjo", name: "Anjo", bonus: { pod: 3, res: 2 }, passive: "Aura Divina: escolhe um juramento; proteção e cura são estáveis enquanto o voto é respeitado." },
        { id: "demonio", name: "Demônio", bonus: { for: 3, pod: 2 }, passive: "Fúria Infernal: eleva a intensidade de uma ação ao aceitar consequência proporcional antes do uso." },
        { id: "vampiro", name: "Vampiro", bonus: { vel: 3, pod: 2 }, passive: "Vampirismo: alimentação consentida ou autorizada recupera essência gradualmente e revela ecos emocionais." },
        { id: "zoofolk", name: "Zoofolk", bonus: { for: 2, vel: 2, res: 1 }, passive: "Instinto Bestial: escolhe um traço animal registrado, sem receber todas as capacidades da espécie." },
        { id: "anao", name: "Anão", bonus: { res: 3, for: 2 }, passive: "Sangue da Forja: mantém estabilidade sob calor, peso, vibração ou trabalho prolongado." },
        { id: "draconato", name: "Draconato", bonus: { for: 2, pod: 2, res: 1 }, passive: "Presa Dracônica: escolhe sopro limitado, escamas, sentidos térmicos ou presença predatória." },
        { id: "morto-vivo", name: "Morto-Vivo Consciente", bonus: { res: 3, pod: 2 }, passive: "Memória Fúnebre: não respira e resiste a fadiga comum, mas depende de âncora de identidade." },
        { id: "silvanico", name: "Silvânico", bonus: { res: 2, pod: 2, hab: 1 }, passive: "Canto Verde: percebe estados simples de plantas e desequilíbrios naturais próximos." },
        { id: "lunariano", name: "Lunariano", bonus: { pod: 2, vel: 2, hab: 1 }, passive: "Maré Onírica: recorda sonhos e padrões emocionais em locais marcados por lua ou água." },
        { id: "sombranato", name: "Sombranato", bonus: { vel: 2, hab: 2, pod: 1 }, passive: "Véu da Penumbra: reduz presença visual e sonora na sombra enquanto se move com cautela." },
        { id: "maresio", name: "Marésio", bonus: { res: 2, hab: 2, pod: 1 }, passive: "Pulmão de Duas Águas: respira em água e ar e percebe correntes; seca exige hidratação." },
        { id: "forjado", name: "Forjado", bonus: { res: 3, for: 1, pod: 1 }, passive: "Núcleo Vinculado: resiste a venenos orgânicos e pode ser reparado, mas exige manutenção." },
        { id: "cineriano", name: "Cineriano", bonus: { pod: 2, res: 2, vel: 1 }, passive: "Pulso de Cinza: tolera fumaça e reconhece combustão; água e vento dispersam seus vestígios." },
        { id: "titanico", name: "Titânico", bonus: { for: 3, res: 2 }, passive: "Corpo de Monumento: sustenta peso e impacto, mas perde furtividade e sofre em espaços estreitos." },
      ],
      classes: [
        { id: "acolito", name: "Acólito", bonus: { pod: 2, res: 1 }, role: "Suporte, cura, proteção, ritos e vínculos espirituais.", paths: "Guardião do Voto · Curador de Cinzas · Exorcista do Véu · Sacerdote de Guerra · Condutor de Essência" },
        { id: "mago", name: "Mago", bonus: { pod: 3 }, role: "Estudo sobrenatural, fórmulas, controle, invocação e leitura arcana.", paths: "Arcanista de Guerra · Tecelão de Ritos · Invocador · Cronomante Limitado · Pesquisador do Impossível" },
        { id: "guerreiro", name: "Guerreiro", bonus: { for: 2, res: 1 }, role: "Combate direto, armas, guarda, ruptura de linhas e disciplina física.", paths: "Bastião · Duelista · Quebra-Cerco · Cavaleiro Rúnico · Comandante" },
        { id: "ladino", name: "Ladino", bonus: { vel: 2, hab: 1 }, role: "Furtividade, precisão, infiltração, armadilhas e informação.", paths: "Infiltrador · Caçador de Monstros · Atirador · Estrategista de Rua · Sentinela das Cortinas" },
      ],
      affinityCategories: [
        { id: "elemental", name: "Elemental", weight: 50, rarity: "Comum", color: "#d7b962", description: "Forças estáveis, estudadas e socialmente comuns." },
        { id: "sub-elemental", name: "Subelemental", weight: 25, rarity: "Incomum", color: "#72a5c4", description: "Domínios especializados que dependem de matéria ou condição." },
        { id: "espiritual", name: "Espiritual", weight: 13, rarity: "Raro", color: "#9883c8", description: "Mente, alma, símbolo, memória e vínculo." },
        { id: "celestial", name: "Celestial", weight: 8, rarity: "Épico", color: "#ead17b", description: "Ciclos, juramentos e fenômenos superiores." },
        { id: "cosmica", name: "Cósmica", weight: 4, rarity: "Cósmica", color: "#c7b7ef", description: "Forças raras, instáveis, perigosas e difíceis de controlar." },
      ],
      affinities: [
        affinity("fogo", "Fogo", "elemental", { pod: 2 }, "Calor, chama e combustão.", "Oxigênio, combustível, energia e risco de incêndio."),
        affinity("agua", "Água", "elemental", { res: 1, pod: 1 }, "Fluxo, pressão, defesa e mudança de estado.", "Fonte e volume importam; corpos vivos não são controlados."),
        affinity("terra", "Terra", "elemental", { res: 2 }, "Solo, rocha, apoio e cobertura.", "Massa, terreno e mobilidade limitam o uso."),
        affinity("ar", "Ar", "elemental", { vel: 2 }, "Impulso, corrente, som e pressão.", "Espaço fechado, ausência de ar e turbulência contrária."),
        affinity("relampago", "Relâmpago", "sub-elemental", { vel: 1, hab: 1 }, "Condução elétrica e aceleração curta.", "Sobrecarga nervosa, aterramento e isolantes."),
        affinity("gelo", "Gelo", "sub-elemental", { res: 1, hab: 1 }, "Retirada de calor e controle de terreno.", "Fogo, impacto, umidade e custo térmico."),
        affinity("magma", "Magma", "sub-elemental", { for: 1, pod: 1 }, "Calor extremo, massa e cerco.", "Lento, visível e perigoso para aliados."),
        affinity("nevoa", "Névoa", "sub-elemental", { vel: 1, hab: 1 }, "Ocultação e dispersão visual.", "Vento, calor e sentidos não visuais."),
        affinity("veneno", "Veneno", "sub-elemental", { pod: 1, res: 1 }, "Toxinas, corrosão e efeitos progressivos.", "Via de entrada, tempo, antídotos e compatibilidade."),
        affinity("cristal", "Cristal", "sub-elemental", { res: 1, hab: 1 }, "Estruturas, condução e armazenamento.", "Fraturas, ressonância e choque térmico."),
        affinity("metal", "Metal", "sub-elemental", { for: 1, res: 1 }, "Armas, armaduras, reforço e magnetismo limitado.", "Fonte, peso, corrosão e ligas resistentes."),
        affinity("natureza", "Natureza", "sub-elemental", { res: 1, pod: 1 }, "Plantas, raízes, simbiose e restauração gradual.", "Matéria viva, tempo, ambiente e ciclos."),
        affinity("areia", "Areia", "sub-elemental", { pod: 1, hab: 1 }, "Erosão, ocultação e matéria granular.", "Água, compactação e ausência de material."),
        affinity("espirito", "Espírito", "espiritual", { pod: 2 }, "Almas, ecos, entidades e planos sutis.", "Abertura espiritual, dívida, possessão e proteção ritual."),
        affinity("psiquica", "Psíquica", "espiritual", { pod: 1, hab: 1 }, "Telepatia limitada, pressão mental e telecinese técnica.", "Concentração, distância e consentimento para controle profundo."),
        affinity("sombras", "Sombras", "espiritual", { vel: 1, pod: 1 }, "Ocultação, formas e conexão entre sombras.", "Luz, ausência de sombra e necessidade de âncoras."),
        affinity("luz", "Luz", "espiritual", { pod: 1, hab: 1 }, "Revelação, purificação, cura e energia radiante.", "Exposição, custo e natureza específica da corrupção."),
        affinity("sangue", "Sangue", "espiritual", { res: 2 }, "Rastreio, pacto, vitalidade e próprio sangue.", "Perda de sangue, fome, consentimento e risco biológico."),
        affinity("arcana", "Arcana", "espiritual", { pod: 2 }, "Fórmulas e energia mágica versátil.", "Estudo, símbolos, foco e custo maior ao improvisar."),
        affinity("celestial", "Celestial", "celestial", { pod: 1, res: 1 }, "Bênçãos, selos, proteção e juramentos.", "Votos e Fratura ao contradizer a fonte."),
        affinity("lunar", "Lunar", "celestial", { vel: 1, pod: 1 }, "Ciclos, sonhos, reflexos e recuperação.", "Ciclo, água, ambiente e estabilidade emocional."),
        affinity("solar", "Solar", "celestial", { for: 1, pod: 1 }, "Calor puro, pressão luminosa e presença.", "Consumo elevado e difícil ocultação."),
        affinity("estelar", "Estelar", "celestial", { hab: 1, pod: 1 }, "Orientação, padrões, precisão e trajetórias.", "Mapas, cálculos, constelações ou âncoras."),
        affinity("eter", "Éter", "cosmica", { pod: 2 }, "Energia primordial que assume formas diversas.", "Instabilidade, especialização difícil e reação com outras afinidades."),
        affinity("gravidade", "Gravidade", "cosmica", { for: 1, pod: 1 }, "Atração, pressão e alteração de peso.", "Afeta usuário e cenário; grande área exige preparação."),
        affinity("vazio", "Vazio", "cosmica", { vel: 1, pod: 1 }, "Ausência, silêncio, erosão e ocultação extrema.", "Erosão de memória, emoção e identidade."),
        affinity("meteoro", "Meteoro", "cosmica", { for: 1, hab: 1 }, "Momentum, queda e impacto dirigido.", "Trajetória, espaço, aceleração e difícil interrupção."),
        affinity("tempo", "Tempo", "cosmica", { vel: 1, hab: 1 }, "Percepção acelerada, atraso e compressão local.", "Não reescreve o passado; cobra memória, idade ou orientação."),
        affinity("espaco", "Espaço", "cosmica", { hab: 1, pod: 1 }, "Dobras curtas, armazenamento e âncoras.", "Não atravessa desconhecido ou selos sem marca."),
        affinity("cinzas", "Cinzas", "sub-elemental", { pod: 1, res: 1 }, "Vestígios de combustão e memória térmica.", "Vento, água, falta de cinza e dispersão.", true),
        affinity("madeira", "Madeira", "sub-elemental", { res: 1, hab: 1 }, "Fibras, raízes e ferramentas vivas.", "Umidade, matéria existente, pragas e fogo.", true),
        affinity("vidro", "Vidro", "sub-elemental", { hab: 1, pod: 1 }, "Lentes, lâminas, reflexos e registros frágeis.", "Impacto, choque térmico e matéria-prima.", true),
        affinity("ferrugem", "Ferrugem", "sub-elemental", { pod: 1, hab: 1 }, "Corrosão e desgaste de metal exposto.", "Contato, tempo, ligas e proteção.", true),
        affinity("fumaca", "Fumaça", "sub-elemental", { vel: 1, pod: 1 }, "Cobertura, calor residual e partículas.", "Vento, filtros, água e risco respiratório.", true),
        affinity("som", "Som", "sub-elemental", { hab: 1, pod: 1 }, "Vibração, ressonância e ruptura acústica.", "Silêncio, vácuo, isolamento e dano auditivo.", true),
        affinity("osso", "Osso", "sub-elemental", { for: 1, res: 1 }, "Reforço do próprio esqueleto e leitura de restos.", "Dor, fratura, cálcio e limites do corpo.", true),
        affinity("tinta", "Tinta", "sub-elemental", { hab: 1, pod: 1 }, "Selos, marcas, ilusão gráfica e contratos.", "Superfície, secagem, apagamento e interpretação.", true),
        affinity("eco", "Eco", "espiritual", { hab: 1, pod: 1 }, "Registra sons e impressões recentes.", "Ruído, distância, fidelidade e tempo.", true),
        affinity("memoria", "Memória", "espiritual", { pod: 2 }, "Preserva e compartilha lembranças oferecidas.", "Consentimento, distorção, trauma e custo emocional.", true),
        affinity("sonho", "Sonho", "espiritual", { pod: 1, hab: 1 }, "Comunicação e símbolos durante o sono.", "Alvo adormecido, interpretação e risco psíquico.", true),
        affinity("juramento", "Juramento", "espiritual", { res: 1, pod: 1 }, "Votos, contratos e promessas declaradas.", "Texto claro, testemunho e punição bilateral.", true),
        affinity("dor", "Dor", "espiritual", { res: 2 }, "Percebe e transforma dor com consentimento.", "Trauma, sobrecarga e nunca remove a causa.", true),
        affinity("musica", "Música", "espiritual", { hab: 1, pod: 1 }, "Ritmo, memória, emoção e sincronia.", "Audição, execução, concentração e consentimento.", true),
        affinity("aurora", "Aurora", "celestial", { res: 1, pod: 1 }, "Purificação gradual, transição e luz polar.", "Contraste entre treva e luz; visível e instável.", true),
        affinity("eclipse", "Eclipse", "celestial", { vel: 1, pod: 1 }, "Interseção entre luz e sombra.", "Duração curta, alto custo e efeito no usuário.", true),
        affinity("cometa", "Cometa", "celestial", { vel: 1, hab: 1 }, "Trajetória, presságio e impulso luminoso.", "Rota definida e rastro perceptível.", true),
        affinity("constelacao", "Constelação", "celestial", { hab: 1, pod: 1 }, "Redes de pontos, vínculos e mapas possíveis.", "Exige pontos marcados; não determina futuro.", true),
        affinity("ruina", "Ruína", "cosmica", { for: 1, pod: 1 }, "Acelera decadência já iniciada.", "Não destrói instantaneamente algo íntegro.", true),
        affinity("abismo", "Abismo", "cosmica", { res: 1, pod: 1 }, "Pressão, silêncio e espaços incompreensíveis.", "Sanidade, orientação e identidade.", true),
        affinity("entropia", "Entropia", "cosmica", { hab: 1, pod: 1 }, "Aumenta desordem em sistemas instáveis.", "Imprevisibilidade atinge aliados e usuário.", true),
        affinity("horizonte", "Horizonte", "cosmica", { res: 1, hab: 1 }, "Limites, contenção e fronteiras dimensionais.", "Não cria prisão absoluta; exige âncora.", true),
        affinity("paradoxo", "Paradoxo", "cosmica", { vel: 1, hab: 1 }, "Mantém duas possibilidades por instantes.", "Colapso inevitável, perda de memória e arbitragem.", true),
      ],
      items: baseItems,
      gachaPets: petSpecs,
      gachaItems: cosmetics,
      gachaShardShops: shardOffers,
      towerMaps: [
        { id: "pantano-dos-sinos", name: "Pântano dos Sinos Afogados", theme: "Mangue funerário", lanes: 2, slots: 6, routeType: "marsh", enemyFaction: "Afogados Sineiros", enemyTrait: "summoner", difficulty: "Hard", imageUrl: "https://res.cloudinary.com/cakvvuqx/image/upload/f_auto,q_auto,w_1440,c_limit/v1783719061/millennium/maps/zefcknkprt8h7uhzzmkd.png", description: "Ilhas estreitas e água móvel; sinos não silenciados convocam reforços." },
        { id: "ermos-da-ferrugem", name: "Ermos da Ferrugem", theme: "Fronteira industrial", lanes: 3, slots: 7, routeType: "rails", enemyFaction: "Máquinas Sem Identidade", enemyTrait: "armored", difficulty: "Pesadelo", imageUrl: "https://res.cloudinary.com/cakvvuqx/image/upload/f_auto,q_auto,w_1440,c_limit/v1783719057/millennium/maps/un0qeu7czwnglelaowc9.png", description: "Esteiras e trilhos mudam a velocidade dos blindados e deixam sucata utilizável." },
        { id: "mar-de-vidro-negro", name: "Mar de Vidro Negro", theme: "Oceano refletido", lanes: 2, slots: 5, routeType: "mirror", enemyFaction: "Reflexos Famintos", enemyTrait: "phase", difficulty: "God Slayer", imageUrl: "https://res.cloudinary.com/cakvvuqx/image/upload/f_auto,q_auto,w_1440,c_limit/v1783719065/millennium/maps/vlxlggz8ud2lvg1js83k.png", description: "Inimigos surgem na rota refletida; tempestades alteram alcance e direção." },
      ],
      kingdoms,
      biomes,
      reputationFactions: factions,
      npcs,
      rulesChapters,
      tutorialSteps,
      faqEntries: [
        { id: "faq-xp", name: "Como ganho XP?", category: "Evolução", answer: "Por cenas substanciais, treinos, duelos, missões, eventos e produção social aprovados. Roletas e minigames não concedem XP narrativo automaticamente." },
        { id: "faq-afinidade", name: "Afinidade é meu poder?", category: "Afinidade", answer: "Não. Afinidade orienta estética, matéria, custo e limites. O Poder central é criado e aprovado separadamente." },
        { id: "faq-minigame", name: "Minigame decide uma missão?", category: "Minigames", answer: "Não. Minigames geram recursos digitais, coleção e ranking; cenas do WhatsApp dependem de interpretação e consequência." },
        { id: "faq-faccao", name: "Por que facções estão bloqueadas?", category: "Mundo", answer: "O primeiro vínculo será aberto pelo Oráculo dentro da história. Conhecer uma facção no Codex não significa pertencer a ela." },
        { id: "faq-item", name: "Item dá vitória automática?", category: "Itens", answer: "Não. Qualidade, função, tags e limite autorizam possibilidades; posição, material, preparo e resposta continuam importantes." },
        { id: "faq-pet", name: "Meu pet pode morrer?", category: "Pets", answer: "Somente em risco explicitamente aceito e quando o servidor habilitar essa regra. Ferido, Grave e Perdido criam descanso, tratamento ou missão de resgate." },
        { id: "faq-oraculo", name: "Quando chamar o Oráculo?", category: "Ajuda", answer: "Quando houver disputa sem consenso, elemento do mundo, denúncia, aprovação sensível ou erro que a autonomia normal não resolve." },
      ],
      marketListings,
      auctionListings: [
        { id: "lamina-celeste", name: "Lâmina Celeste", rarity: "Épico", minBid: 500, endsAt: future(3), description: "Aço votivo retirado da Sociedade das Lâminas." },
        { id: "leilao-coroa-sol-partido", name: "Coroa do Sol Partido", rarity: "Lendário", minBid: 850, endsAt: future(4), description: "Relíquia política de Solcaris; sua posse chama atenção da Igreja." },
        { id: "leilao-mapa-ultima-porta", name: "Mapa da Última Porta", rarity: "Mítico", minBid: 1200, endsAt: future(5), description: "Cartografia incompleta de uma saída das Cortinas." },
        { id: "leilao-sino-afogado", name: "Sino Afogado", rarity: "Raro", minBid: 380, endsAt: future(6), description: "Bronze funerário que ecoa próximo de mortos inquietos." },
        { id: "leilao-nome-persistente", name: "Selo de Nome Persistente", rarity: "Cósmica", minBid: 1900, endsAt: future(7), description: "Âncora jurídica e espiritual de Vel-Khar." },
      ],
      craftingRecipes: [
        { id: "receita-lanterna-cortina", name: "Lanterna da Cortina", rarity: "Raro", materials: "Fibra de Eco x5 + Cinza fria x8", result: "Lanterna da Cortina", description: "Revela encontros secretos em incursões." },
        { id: "receita-broche-neve", name: "Broche da Neve Oca", rarity: "Épico", materials: "Galhada lunar x2 + Couro pálido x6", result: "Broche da Neve Oca", description: "Cosmético e relíquia do Norte Branco." },
        { id: "receita-aco-votivo", name: "Lâmina de Aço Votivo", rarity: "Épico", materials: "Aço votivo x8 + Runas Partidas x4", result: "Lâmina de Aço Votivo", description: "Arma que registra um juramento e sua contramedida." },
        { id: "receita-espelho-abissal", name: "Espelho Abissal", rarity: "Lendário", materials: "Vidro abissal x6 + Sal lunar x10", result: "Espelho Abissal", description: "Relíquia que conserva um reflexo de identidade." },
        { id: "receita-kit-hunt", name: "Kit de Hunt Profunda", rarity: "Incomum", materials: "Ervas de pântano x4 + Corda 15 m x1 + Ração de Viagem x2", result: "Kit de Hunt Profunda", description: "Suprimentos preparados para incursões longas." },
        { id: "receita-nucleo-runico", name: "Núcleo Rúnico", rarity: "Raro", materials: "Sucata arcana x10 + Núcleo opaco x2", result: "Núcleo Rúnico", description: "Componente para itens digitais e Tower Defense." },
      ],
      worldLore: [
        { id: "origem-millennium", name: "A Máquina Funerária", era: "Verdade proibida", summary: "Millennium pode alimentar a Interface com memória, desejo e conflito.", description: "A doutrina chama o mundo de solo sagrado. Arquivos apagados sugerem uma segunda condenação construída sobre mundos mortos." },
        { id: "interface-oraculo", name: "A Interface do Oráculo", era: "Ano 317", summary: "Vidro escuro, runas e luz contida registram escolhas reconhecidas.", description: "A Janela não é onisciente: pode ser enganada, corrompida, silenciada e contradita." },
        { id: "treze-tumulos", name: "Os Treze Túmulos", era: "Despertar dos Heróis", summary: "Treze sepulturas abriram na mesma noite.", description: "Os antigos Heróis eram recipientes de fragmentos divinos. O processo começou a se repetir." },
        { id: "marca-heroica", name: "Marca Heroica", era: "Temporada I", summary: "Virtude e Horror nascem de um feito com risco e consequência pública.", description: "A Marca não vem de gacha. Aceitá-la concede permissão narrativa e obrigação transformadora." },
        { id: "frentes-temporada", name: "As Quatro Frentes", era: "Mundo vivo", summary: "Reconhecimento, Sepulturas, Guerra e Incubação avançam com ações coletivas.", description: "A temporada não possui episódios; cada Frente pode progredir, recuar ou se dividir." },
      ],
      wantedBoard: [
        { id: "criança-sem-rosto", name: "A Criança Sem Rosto", rarity: "Mítico", reward: "Acesso a cadeia Secret", description: "Vista entrando em registros que a Interface insiste não possuir." },
        { id: "colecionador-halos", name: "Colecionador de Halos", rarity: "Épico", reward: "420 PO + fragmento celestial", description: "Compra, rouba e quebra halos de anjos fraturados." },
        { id: "ferreiro-nove-dedos", name: "Ferreiro dos Nove Dedos", rarity: "Raro", reward: "260 PO", description: "Vende núcleos adulterados nas rotas de Grivemarch." },
        { id: "eco-aurelian", name: "Eco de Aurelian I", rarity: "Lendário", reward: "Audiência em Solcaris", description: "Um rei morto continua emitindo ordens a soldados vivos." },
      ],
      bestiary: [
        { id: "sentinela-vidro", name: "Sentinela de Vidro", rarity: "Raro", region: "Mar de Vidro Negro", weakness: "Impacto e som", drops: "Vidro abissal · Núcleo opaco", description: "Construto que reflete magia previsível." },
        { id: "afogado-sineiro", name: "Afogado Sineiro", rarity: "Incomum", region: "Pântano dos Sinos", weakness: "Silêncio ritual", drops: "Bronze fúnebre · Ervas de pântano", description: "Morto guiado pelo som de torres submersas." },
        { id: "predador-sem-rastro", name: "Predador Sem Rastro", rarity: "Épico", region: "Folhas Douradas", weakness: "Memória compartilhada", drops: "Seiva memorial · Madeira viva", description: "Apaga o próprio rastro da lembrança de quem o persegue." },
        { id: "maquina-sem-identidade", name: "Máquina Sem Identidade", rarity: "Lendário", region: "Ermos da Ferrugem", weakness: "Nome verdadeiro do núcleo", drops: "Sucata arcana · Núcleo rúnico", description: "Protótipo criado quando a cópia da Janela escolheu um corpo." },
        { id: "jardineiro-de-carne", name: "Jardineiro de Carne", rarity: "Mítico", region: "Jardins de Carne", weakness: "Fogo controlado e anestesia", drops: "Fibra viva · Glândula divina", description: "Cultiva feridas como flores para um deus enterrado." },
      ],
    },
  };
}());
